services:
  cli-db:
    image: postgres:15
    container_name: cli-db
    restart: always
    environment:
      POSTGRES_DB: cli
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: fhs8i.xbfroq.sgdfu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  django-scaper:
    build: .
    container_name: django-scaper
    volumes:
      - ./src:/app
    ports:
      - "8100:8000"
    working_dir: /app
    depends_on:
      - cli-db
    environment:
      DB_HOST: cli-db
      DB_PORT: 5432
      DB_NAME: cli
      DB_USER: scraper
      DB_PASSWORD: fhs8i.xbfroq.sgdfu
      DATABASE_URL: postgres://scraper:fhs8i.xbfroq.sgdfu@cli-db:5432/cli

volumes:
  postgres_data:

