# Generated by Django 5.2 on 2025-04-18 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL della pagina')),
                ('level', models.IntegerField(help_text='Livello gerarchico (intero)')),
                ('hash_content', models.CharField(help_text='Hash del contenuto (tipicamente SHA‑256, 64 caratteri esadecimali)', max_length=64)),
                ('from_id', models.ForeignKey(blank=True, db_column='from_id', help_text='Riferimento (ID) alla pagina da cui è derivata', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='infrastructure.page')),
            ],
            options={
                'db_table': 'pages',
            },
        ),
    ]
